spring.application.name=student-management
server.port=${PORT:8080}

# Database (PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-still-cell-a1w82267-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_5WAX6KRbSilk}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL init
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT_MODE:always}
