INSERT INTO students (id, name, email, age) VALUES ('1', 'Nguyen Van A', 'vana@example.com', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2', 'Tran Thi B', 'thib@example.com', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('3', 'Le Van C', 'vanc@example.com', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('4', 'Pham Thi D', 'thid@example.com', 19) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('5', 'Hoang Van E', 'vane@example.com', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('6', 'Nguyen Thi F', 'thif@example.com', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('7', 'Vo Van G', 'vang@example.com', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('8', 'Dang Thi H', 'thih@example.com', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('9', 'Bui Van I', 'vani@example.com', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('10', 'Ly Thi K', 'thik@example.com', 19) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('11', 'Truong Van L', 'vanl@example.com', 24) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('12', 'Do Thi M', 'thim@example.com', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210412', 'BÙI THẾ CƯƠNG', 'cuong.buitheky@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2310836', 'CẤN HÀ', 'ha.canhoang2005@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2311942', 'CAO LỘC', 'loc.cao1102@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2310211', 'ĐẶNG BẢO', 'bao.dangnguyen@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212548', 'ĐẶNG PHONG', 'phong.dang2212548@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212610', 'ĐỖ ĐÌNH PHÚC', 'phuc.do2212610@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211035', 'ĐỖ PHÚ HIỂN', 'hien.dokhmt@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213449', 'ĐOÀN TIẾN', 'tien.doan541@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211322', 'ĐOÀN HÙNG', 'hung.doantrymybest@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210787', 'HOÀNG ĐỨC', 'duc.hoang2004k22@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210986', 'HOÀNG HIẾU', 'hieu.hoangminh832004@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211876', 'HOÀNG LONG', 'long.hoang130704@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213173', 'HUỲNH THẠCH', 'thach.huynhthach0712@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2314014', 'HUỲNH VỸ', 'vy.huynhnguyenvy@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210731', 'HUỲNH TRẦN ĐĂNG', 'dang.huynhdang01@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213549', 'LÂM TRANG', 'trang.lambk22@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213276', 'LÂM THỊNH', 'thinh.lam220304@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212220', 'LÊ NGHĨA', 'nghia.lekhmtk22@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211753', 'LÊ KIỆT', 'kiet.levnqwerty@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2311982', 'LÊ LUÂN', 'luan.le2311982@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212046', 'LÊ MINH', 'minh.le1710@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2110770', 'NGÔ BÁCH', 'bach.ngoshadow@hcmut.edu.mockdata', 24) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213491', 'NGUYỄN TÍN', 'tin.nguyentidz1476@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213242', 'NGUYỄN THIẾT', 'thiet.nguyen6868@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213696', 'NGUYỄN TRUNG', 'trung.nguyenbkhcm@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2311436', 'NGUYỄN CHÍ KHANG', 'khang.nguyen2311436@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2313119', 'NGUYỄN THÀNH', 'thanh.nguyenkhmt4205@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210510', 'NGUYỄN DUY', 'duy.nguyen1010fight@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2313280', 'NGUYỄN THỊNH', 'thinh.nguyenalexbk@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210736', 'NGUYỄN ĐĂNG', 'dang.nguyen106@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212059', 'NGUYỄN MINH', 'minh.nguyenhongk22@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2311449', 'NGUYỄN KHANG', 'khang.nguyenkhanghuu14@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2310393', 'NGUYỄN HỮU CƯỜNG', 'cuong.nguyenhuuthien@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2312701', 'NGUYỄN PHÚC', 'phuc.nguyenphucnm266@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213059', 'NGUYỄN TÂN', 'tan.nguyennhat2k4@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213203', 'NGUYỄN THẮNG', 'thang.nguyengiorno@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213205', 'NGUYỄN THẮNG', 'thang.nguyenquoc2004@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2313870', 'NGUYỄN THỊ VÂN', 'van.nguyennhe2005@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('1915866', 'Nguyễn Trần Uy', 'uy.nguyen.this@hcmut.edu.mockdata', 26) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212370', 'NGUYỄN NHÂN', 'nhan.nguyenxxx04@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210590', 'NGUYỄN DŨNG', 'dung.nguyenvan3864@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2312538', 'ÔN HÀ NHƯ', 'nhu.onhangoc@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210400', 'PHẠM CHƯƠNG', 'chuong.phamwarclork@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2310143', 'PHẠM NGUYỄN ANH', 'anh.pham2005@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210714', 'PHẠM ĐẠT', 'dat.phamtuan@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212535', 'SƠN PHÁT', 'phat.son200x@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213897', 'TRẦN UY', 'uy.tranhphtfml@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211644', 'TRẦN KHOA', 'khoa.trananhcse2004@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2312816', 'TRẦN QUẢNG', 'quang.tranhongquang@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2212822', 'TRẦN QUÂN', 'quan.tranminh411@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2214061', 'TRẦN NGỌC VỸ', 'vy.tranngoclamvy@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2310979', 'TRẦN PHẠM HIẾU', 'hieu.tran3125@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211560', 'TRẦN KHẢI', 'khai.trantien1922@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('1810852', 'Trần Cường', 'cuong.tranvan@hcmut.edu.mockdata', 27) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2211350', 'TRỊNH HÙNG', 'hung.trinhminh1904@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2213313', 'TRƯƠNG THỊNH', 'thinh.truong21092004@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2311708', 'VÕ CÔNG KHÔI', 'khoi.vo2311708@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2210834', 'VÕ GIANG', 'giang.voninh@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2252822', 'VŨ TOÀN', 'toan.vuduc2004@hcmut.edu.mockdata', 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO students (id, name, email, age) VALUES ('2313523', 'VŨ THỊ TRANG', 'trang.vutrang@hcmut.edu.mockdata', 22) ON CONFLICT (id) DO NOTHING;
